apiVersion: v1
kind: Namespace
metadata:
  name: doris

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
      - name: hola-mundo-container
        image: rgguerrero/test_docker:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 10

